### ISSUE TITLE
xslt stylesheet support removed?

### ISSUE THREAD

**Issue by tomascohen** [timbrody/perl-oai-lib#11]
Hi, is there a reason for ->xslt to get removed from the api? Before the changes we were able to do $response->xslt = 'path_to_xslt'

**Comment by tomascohen** [comment]
It looks like the code injecting the stylesheet reference in HTTP::OAI::Response:generate has been removed.

**Comment by phochste** [comment]
@tomascohen Hi, the maintenance of perl-oai-lib has been move to https://github.com/LibreCat/perl-oai-lib could you open a ticket there so we can follow up?

**Comment by tomascohen** [comment]
Sure, @phochste
