### ISSUE TITLE
Test t/getrecord.t fails

### ISSUE THREAD

**Issue by fredericd** [timbrody/perl-oai-lib#9]
When running this specific test:

  `prove -v -l blib t/getrecord.t`

The last test fails:

`Can't call method "start_element" on an undefined value at /home/tamil/util/perl-oai-lib/lib/HTTP/OAI/Verb.pm line 53.`

Are you working on a solution? Is there anything I can do?

**Comment by phochste** [comment]
This error can be reproduced by installing XML::SAX::Writer

**Comment by phochste** [comment]
Fixed in 4.04
